server:
  port: 14000
#  ssl:
#    enabled: true
#    key-alias: outStudyKey
#    key-password: qkseltqnfdl
#    key-store: C:\Users\roseoutz\IdeaProjects\btaka-project\outStudy.p12

logging:
  level:
    org:
      springframework:
        data:
          mongodb: trace


btaka:
  oauth:
    redirect:
      url: http://localhost:14000/api/v1/sns/result
  social:
    kakao:
      client-id: 735b21c68f4ab7d810f8ca1e1578e69e
      client-secret: 9TBmgIcg3GorCALh7tQ6Zc76G5WCXRwo
      auth-url: https://kauth.kakao.com/oauth/authorize
      token-url: https://kauth.kakao.com/oauth/token
      user-info-url: https://kapi.kakao.com/v2/user/me
    github:
      client-id: 4c1db9681216f8ee8dcf
      client-secret: c9ed0a03221f70a56c3e8c89e59460788ac71983
      auth-url: https://github.com/login/oauth/authorize
      token-url: https://github.com/login/oauth/access_token
      user-info-url: https://api.github.com/user
    google:
      client-id: 103151941059-t8461squ0sjjcvp6utkr192p2keke4am.apps.googleusercontent.com
      client-secret: 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
      auth-url: https://accounts.google.com/o/oauth2/v2/auth
      token-url: https://oauth2.googleapis.com/token
      user-info-url: https://www.googleapis.com/oauth2/v1/userinfo
    facebook:
      client-id: 510459117161974
      client-secret: ae1e334395ed15ff7d7007dfcfaf57e0
      auth-url: https://www.facebook.com/v13.0/dialog/oauth
      token-url: https://graph.facebook.com/v13.0/oauth/access_token
      user-info-url: https://www.googleapis.com/oauth2/v1/userinfo
  value:
    jwt:
      secret: btaka-jwt-service-hahahahahahahaha
      tokenMaxValidTime: 86400

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:12000/eureka/
  instance:
    hostname: authService
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /v3/api-docs/swagger.html

spring:
  application:
    name: btaka-auth-service
  redis:
    host: 127.0.0.1
    port: 6379
  data:
    mongodb:
      host: 127.0.0.1
      username: firefly
      password: qkseltqnfdl
      database: btaka_user
      authentication-database: admin
      repositories:
        type: reactive