server:
  port: 14000

logging:
  level:
    org:
      springframework:
        data:
          mongodb: trace


btaka:
  value:
    jwt:
      secret: btaka-jwt-service-hahahahahahahaha
      tokenMaxValidTime: 86400

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:12000/eureka/
  instance:
    hostname: authService
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

spring:
  application:
    name: btaka-auth-service
  redis:
    host: localhost
    port: 6379
  data:
    mongodb:
      host: localhost
      username: firefly
      password: qkseltqnfdl
      database: user
      authentication-database: admin
      repositories:
        type: reactive


