server:
  port: 14000

logging:
  level:
    org:
      springframework:
        data:
          mongodb: trace


btaka:
  oauth:
    redirect:
      url: http://localhost:14000/api/v1/sns/result
  social:
    kakao:
      client-id: 71eceb279c8b62a011f4a83cb3a76931
      client-secret: KMY40epEVg6Fd3Kp0LT647JXDZdooE89
      auth-url: https://kauth.kakao.com/oauth/authorize
      token-url: https://kauth.kakao.com/oauth/token
      user-info-url: https://kapi.kakao.com/v2/user/me
  value:
    jwt:
      secret: btaka-jwt-service-hahahahahahahaha
      tokenMaxValidTime: 86400

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:1200/eureka/
  instance:
    hostname: authService
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /v3/api-docs/swagger.html

spring:
  application:
    name: btaka-auth-service
  redis:
    host: 127.0.0.1
    port: 6379
  data:
    mongodb:
      host: 127.0.0.1
      username: firefly
      password: qkseltqnfdl
      database: btaka_user
      authentication-database: admin
      repositories:
        type: reactive


