server:
  port: 10000

logging:
  level:
    org:
      springframework:
        data:
          mongodb: trace

spring:
  redis:
    host: localhost
    port: 6379

  data:
    mongodb:
      host: localhost
      username: firefly
      password: qkseltqnfdl
      database: btaka
      authentication-database: admin