server:
  port: 13000

btaka:
  value:
    jwt:
      secret: btaka-jwt-service-hahahahahahahaha
      tokenMaxValidTime: 86400

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:12000/eureka/
  instance:
    hostname: boardDevStudyService
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

spring:
  application:
    name: btaka-board-dev-study-service
  profiles:
    active: test

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    hikari:
      jdbc-url: jdbc:log4jdbc:h2:mem:ourStudy;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      username: sa
      password:
      pool-name: hikari-db-pool
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    hikari:
      jdbc-url: jdbc:log4jdbc:postgresql:localhost:5431/osd_board_dev
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      username: firefly
      password: qkseltqnfdl
      pool-name: hikari-db-pool
      maximum-pool-size: 50
      connection-timeout: 10000
      validation-timeout: 5000
      auto-commit: false
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    show-sql: true
    properties:
      hibernate:
        hql:
          bulk_id_strategy: org.hibernate.hql.spi.id.inline.InlineIdsInClauseBulkIdStrategy
